name: docker_bot
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.5.2

# Add regular dependencies here.
dependencies:
  mineral: ^4.0.0-dev.4
  mineral_cache: ^1.0.0-dev.2

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
