apiVersion: apps/v1
kind: Deployment

metadata:
  name: {{ .Release.Name }}-kube-test
  namespace: {{ .Release.Namespace }}
  labels:
    app: kube-test
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: kube-test
  template:
    metadata:
      labels:
        app: kube-test
    spec:
      containers:
        - name: {{ .Release.Name }}-kube-test
          image: "{{ .Values.image.registry }}/{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          env:
            - name: DART_ENV
              value: {{ .Values.dartEnv | quote  }}
            - name: HTTP_VERSION
              value: {{ .Values.httpVersion | quote  }}
            - name: WSS_VERSION
              value: {{ .Values.wssVersion | quote  }}
            - name: INTENT
              value: {{ .Values.intent | quote  }}
            - name: LOG_LEVEL
              value: {{ .Values.logLevel | quote  }}
            - name: TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.kubeSecret }}
                  key: token
      imagePullSecrets:
        - name: "{{ .Values.image.pullSecretName }}"
