apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-kube_test
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: kube_test
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3333
